// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testsystem.context;

namespace testsystem.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20180911085956_BuildUpRelations")]
    partial class BuildUpRelations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("testsystem.models.Candidat", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("ExpiredDate");

                    b.Property<long>("InvitationDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Number");

                    b.Property<string>("Phone");

                    b.Property<int?>("PositionId");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Candidats");
                });

            modelBuilder.Entity("testsystem.Models.Position", b =>
                {
                    b.Property<int>("Id");

                    b.Property<long>("CloseDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Number");

                    b.Property<long>("OpenDate");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("testsystem.models.Viewer", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("InvitationDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Viewers");
                });

            modelBuilder.Entity("testsystem.models.Candidat", b =>
                {
                    b.HasOne("testsystem.Models.Position", "Position")
                        .WithMany("Candidats")
                        .HasForeignKey("PositionId");
                });
#pragma warning restore 612, 618
        }
    }
}
